"""initial tables

Revision ID: b394345ca7cf
Revises: 
Create Date: 2026-02-08 02:20:42.786236

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b394345ca7cf'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_place_id'), 'providers', ['place_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('preferred_times', sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('preferred_days', sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('avoid_times', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('max_distance_km', sa.Float(), server_default=sa.text('10.0'), nullable=False),
    sa.Column('min_rating', sa.Float(), server_default=sa.text('4.0'), nullable=False),
    sa.Column('preferred_providers', sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('blocked_providers', sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('language_preference', sa.String(length=50), server_default=sa.text("'english'"), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('searching', 'shortlisting', 'calling', 'collecting', 'ranking', 'options_ready', 'confirmed', 'cancelled', 'call_failed', name='bookingstatus'), server_default=sa.text("'searching'"), nullable=False),
    sa.Column('service_type', sa.String(length=255), nullable=False),
    sa.Column('preferred_date', sa.String(length=50), nullable=True),
    sa.Column('preferred_time', sa.String(length=50), nullable=True),
    sa.Column('location_override', sa.String(length=500), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('booking_providers',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('pre_score', sa.Float(), nullable=False),
    sa.Column('travel_minutes', sa.Float(), nullable=True),
    sa.Column('was_called', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'provider_id', name='uq_booking_provider')
    )
    op.create_index(op.f('ix_booking_providers_booking_id'), 'booking_providers', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_providers_provider_id'), 'booking_providers', ['provider_id'], unique=False)
    op.create_table('call_results',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('call_outcome', sa.Enum('slot_offered', 'booked_tentative', 'no_availability', 'voicemail', 'call_failed', 'cancelled', name='calloutcome'), nullable=False),
    sa.Column('available_slot', sa.DateTime(), nullable=True),
    sa.Column('provider_notes', sa.Text(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_results_booking_id'), 'call_results', ['booking_id'], unique=False)
    op.create_index(op.f('ix_call_results_provider_id'), 'call_results', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_results_provider_id'), table_name='call_results')
    op.drop_index(op.f('ix_call_results_booking_id'), table_name='call_results')
    op.drop_table('call_results')
    op.drop_index(op.f('ix_booking_providers_provider_id'), table_name='booking_providers')
    op.drop_index(op.f('ix_booking_providers_booking_id'), table_name='booking_providers')
    op.drop_table('booking_providers')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_providers_place_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
